export type TaskStatus = "done" | "in-progress" | "todo";

export type BacklogTask = {
  title: string;
  status: TaskStatus;
  priority: "P0" | "P1" | "P2" | "P3";
};

export type BacklogSection = {
  slug: string;
  title: string;
  href?: string;
  description: string;
  tasks: BacklogTask[];
};

export const BACKLOG: BacklogSection[] = [
  {
    slug: "site",
    title: "Site-wide",
    description: "Cross-cutting work — SEO, infra, design system.",
    tasks: [
      { title: "Dynamic sitemap.xml (all routes)", status: "done", priority: "P0" },
      { title: "robots.txt", status: "done", priority: "P0" },
      { title: "Site-wide JSON-LD (WebSite + Organization)", status: "done", priority: "P0" },
      { title: "Per-map metadata via layout.tsx", status: "done", priority: "P0" },
      { title: "Dynamic OG image (edge)", status: "done", priority: "P0" },
      { title: "FAQ schema on all main map pages", status: "done", priority: "P0" },
      { title: "BreadcrumbList schema on nested pages", status: "done", priority: "P0" },
      { title: "/about page with data-source attribution", status: "done", priority: "P0" },
      { title: "/legal/trademarks fair-use page", status: "done", priority: "P0" },
      { title: "/backlog public dashboard page", status: "done", priority: "P0" },
      { title: "SiteLogo component on every project page", status: "done", priority: "P0" },
      { title: "Homepage hero downsized, project tiles emphasised", status: "done", priority: "P0" },
      { title: "RelatedMaps internal-linking block on all landings", status: "done", priority: "P0" },
      { title: "Homepage bento-grid with per-map illustrated previews", status: "done", priority: "P0" },
      { title: "Stat strip + NEW ribbon on homepage", status: "done", priority: "P0" },
      { title: "Domain purchase + production deploy", status: "todo", priority: "P0" },
      { title: "Privacy Policy page (AdSense/KVKK/GDPR)", status: "todo", priority: "P0" },
      { title: "Cookie consent banner", status: "todo", priority: "P0" },
      { title: "Contact page", status: "todo", priority: "P0" },
      { title: "Google Search Console verify", status: "todo", priority: "P0" },
      { title: "Analytics (Plausible or GA4)", status: "todo", priority: "P0" },
      { title: "PNG favicon set 32/192/512", status: "todo", priority: "P0" },
      { title: "i18n scaffolding (TR + EN)", status: "todo", priority: "P2" },
      { title: "Blog section for long-tail content", status: "todo", priority: "P2" },
      { title: "Newsletter capture", status: "todo", priority: "P2" },
      { title: "Site-wide search", status: "todo", priority: "P2" },
      { title: "AdSense + Amazon Associates integration", status: "todo", priority: "P3" },
      { title: "PWA (offline support, installable)", status: "todo", priority: "P3" },
      { title: "CI (type-check + build on PR)", status: "todo", priority: "P3" },
      { title: "Uptime monitoring", status: "todo", priority: "P3" },
    ],
  },
  {
    slug: "iss",
    title: "ISS Tracker",
    href: "/maps/iss",
    description: "Live International Space Station tracker with pass predictions.",
    tasks: [
      { title: "3D live globe with ISS marker + telemetry", status: "done", priority: "P0" },
      { title: "95-minute forward orbit path (TLE + satellite.js)", status: "done", priority: "P0" },
      { title: "Passes-over-you predictor with location search", status: "done", priority: "P0" },
      { title: "Sun / shadow status + local time", status: "done", priority: "P0" },
      { title: "Crew roster (Open Notify)", status: "done", priority: "P0" },
      { title: "Distance from user to ISS", status: "done", priority: "P0" },
      { title: "'How to spot the ISS' guide page", status: "done", priority: "P0" },
      { title: "Per-page FAQ schema (main + guide)", status: "done", priority: "P0" },
      { title: "Sun terminator overlay (removed for cleaner visual)", status: "done", priority: "P0" },
      { title: "Spotting guide link in header", status: "done", priority: "P0" },
      { title: "Per-city landing pages (top 50 cities)", status: "todo", priority: "P0" },
      { title: ".ics calendar export per pass", status: "todo", priority: "P1" },
      { title: "Browser notification 10 min before pass", status: "todo", priority: "P1" },
      { title: "Past ground track", status: "todo", priority: "P1" },
      { title: "Visibility filter (twilight passes only)", status: "todo", priority: "P1" },
      { title: "Rise / peak / set compass directions", status: "todo", priority: "P1" },
      { title: "Save favourite locations (localStorage)", status: "todo", priority: "P1" },
      { title: "User location pin on globe", status: "todo", priority: "P1" },
      { title: "Multi-satellite mode (Hubble, Tiangong, Starlink)", status: "todo", priority: "P2" },
      { title: "Apparent magnitude estimate", status: "todo", priority: "P2" },
      { title: "Orbital elements panel", status: "todo", priority: "P2" },
      { title: "30-day altitude sparkline (reboost tracking)", status: "todo", priority: "P2" },
      { title: "Offline TLE-only fallback", status: "todo", priority: "P2" },
    ],
  },
  {
    slug: "taste",
    title: "Taste Passport",
    href: "/maps/taste-passport",
    description: "Gamified bucket-list of the world's signature dishes.",
    tasks: [
      { title: "Country grid + progress + localStorage state", status: "done", priority: "P0" },
      { title: "Dish cards with Wikipedia photo + description", status: "done", priority: "P0" },
      { title: "Tasted / Want / Not-yet status with stamp animation", status: "done", priority: "P0" },
      { title: "Tag every dish (iconic / everyday / street / dessert / drink)", status: "done", priority: "P0" },
      { title: "40+ new 'everyday' dishes added across 8 countries", status: "done", priority: "P0" },
      { title: "Compact 4-column grid, square thumbnails", status: "done", priority: "P0" },
      { title: "Category filter chips (All / Everyday / Street / etc.)", status: "done", priority: "P0" },
      { title: "Icon-only status buttons for DESIGN.md compliance", status: "done", priority: "P0" },
      { title: "Per-country SEO metadata + canonical", status: "done", priority: "P0" },
      { title: "Greece added (13 dishes)", status: "done", priority: "P1" },
      { title: "Vietnam added (12 dishes)", status: "done", priority: "P1" },
      { title: "Dish detail modal (replace page navigation)", status: "todo", priority: "P1" },
      { title: "Add 5 more countries (Georgia, Lebanon, Peru, Spain, Portugal)", status: "todo", priority: "P1" },
      { title: "Shareable passport PNG", status: "todo", priority: "P1" },
      { title: "Personal dashboard with world-map completion colours", status: "todo", priority: "P1" },
      { title: "Diet filter chips (vegetarian, vegan, halal, gluten-free)", status: "todo", priority: "P1" },
      { title: "'Disputed origin' badge per dish", status: "todo", priority: "P1" },
      { title: "Per-dish SEO pages with recipe schema", status: "todo", priority: "P2" },
      { title: "Achievement badges + streaks", status: "todo", priority: "P2" },
      { title: "Pronunciation audio clips", status: "todo", priority: "P2" },
      { title: "Regional cuisine splits (India, Italy, China)", status: "todo", priority: "P2" },
    ],
  },
  {
    slug: "hidden-brands",
    title: "Hidden Brands",
    href: "/maps/hidden-brands",
    description: "Multinational brands that rename themselves across borders.",
    tasks: [
      { title: "Interactive globe with country colour per regional name", status: "done", priority: "P0" },
      { title: "5 initial brands (Heartbrand, Axe/Lynx, BK, Opel, Lay's)", status: "done", priority: "P0" },
      { title: "Wikipedia-sourced logos in legend + click card", status: "done", priority: "P0" },
      { title: "Brand logo thumbnail in 'pick a brand' selector", status: "done", priority: "P0" },
      { title: "Per-brand landing pages with story + FAQ schema", status: "done", priority: "P0" },
      { title: "Mars ↔ Milky Way naming inversion", status: "done", priority: "P0" },
      { title: "Snickers ← Marathon (1990 rebrand)", status: "done", priority: "P0" },
      { title: "Mr. Clean family (6 names)", status: "done", priority: "P0" },
      { title: "Dove / Galaxy chocolate split", status: "done", priority: "P0" },
      { title: "Oil of Olay / Olaz unification story", status: "done", priority: "P0" },
      { title: "Bottom legend strip (DESIGN.md compliance)", status: "done", priority: "P0" },
      { title: "Persistent trademark disclaimer footer + page", status: "done", priority: "P0" },
      { title: "Packaging photo chips next to legend", status: "todo", priority: "P1" },
      { title: "Country-centric pages (/country/tr etc.)", status: "todo", priority: "P1" },
      { title: "Share-card PNG export", status: "todo", priority: "P1" },
      { title: "Historical timeline mode", status: "todo", priority: "P2" },
      { title: "Quiz mode", status: "todo", priority: "P2" },
      { title: "Crowdsource 'Submit a brand' form", status: "todo", priority: "P2" },
      { title: "More brands: Rexona, Persil, Cif, Daewoo, Hilux", status: "todo", priority: "P2" },
    ],
  },
  {
    slug: "visa-free",
    title: "Visa-Free Atlas",
    href: "/maps/visa-free",
    description: "Every passport, every visa requirement, on a 3D globe.",
    tasks: [
      { title: "Full 199×199 matrix rendered on 3D globe", status: "done", priority: "P0" },
      { title: "Hero stat card + onboarding nudge (DESIGN.md pass)", status: "done", priority: "P0" },
      { title: "Permanent bottom legend with icons + one-liners", status: "done", priority: "P0" },
      { title: "199 per-passport landing pages (static)", status: "done", priority: "P0" },
      { title: "Passport power ranking page", status: "done", priority: "P0" },
      { title: "199 inverse destination pages (who can visit X?)", status: "done", priority: "P0" },
      { title: "FAQ schema on main + landing pages", status: "done", priority: "P0" },
      { title: "Cross-linking CTA trio on each passport page", status: "done", priority: "P0" },
      { title: "Auto-detect user's passport (IP/geo hint)", status: "todo", priority: "P0" },
      { title: "Save passport to localStorage", status: "todo", priority: "P1" },
      { title: "Passport comparison mode (A vs B)", status: "todo", priority: "P1" },
      { title: "Region filter (Europe only, Asia only…)", status: "todo", priority: "P1" },
      { title: "Stay-length filter (≥ 90 days only)", status: "todo", priority: "P1" },
      { title: "Share PNG: 'My passport opens N borders'", status: "todo", priority: "P1" },
      { title: "Freedom-of-movement / bloc overlay", status: "todo", priority: "P2" },
      { title: "Dual-citizenship calculator", status: "todo", priority: "P2" },
      { title: "Monthly auto-update from upstream dataset", status: "todo", priority: "P2" },
      { title: "Digital-nomad visa overlay", status: "todo", priority: "P3" },
    ],
  },
  {
    slug: "pilot-game",
    title: "Pilot Game",
    href: "/maps/pilot-game",
    description: "Circle-the-Earth geography guessing game.",
    tasks: [
      { title: "Random spawn + reverse-geocode", status: "done", priority: "P0" },
      { title: "Live 3D globe with plane marker + travelled trail", status: "done", priority: "P0" },
      { title: "Circumnavigation progress bar (km / 40,075)", status: "done", priority: "P0" },
      { title: "Political map (country outlines) for clarity", status: "done", priority: "P0" },
      { title: "20 named seas + specific ocean matching", status: "done", priority: "P0" },
      { title: "Hint system (continent, letter, hemisphere)", status: "done", priority: "P0" },
      { title: "Hangman-style masked answer with initial random letter", status: "done", priority: "P0" },
      { title: "Forward ghost path showing flight direction", status: "done", priority: "P0" },
      { title: "Country autocomplete in guess input", status: "todo", priority: "P0" },
      { title: "Difficulty modes (Easy / Hard / Expert)", status: "todo", priority: "P1" },
      { title: "Share-PNG 'I circled the Earth'", status: "todo", priority: "P1" },
      { title: "High-score localStorage", status: "todo", priority: "P1" },
      { title: "Daily challenge seed", status: "todo", priority: "P1" },
      { title: "Alternative headings (N-S polar, random)", status: "todo", priority: "P2" },
      { title: "Timer mode", status: "todo", priority: "P2" },
      { title: "Multiplayer + leaderboard (backend)", status: "todo", priority: "P3" },
    ],
  },
  {
    slug: "biography",
    title: "Biography Map",
    href: "/maps/biography",
    description: "A famous person's whole life pinned on a 3D globe.",
    tasks: [
      { title: "Wikidata search + SPARQL life-events query", status: "done", priority: "P0" },
      { title: "3D globe with chronological arcs", status: "done", priority: "P0" },
      { title: "Timeline sidebar with icon chips per event", status: "done", priority: "P0" },
      { title: "Legend strip for event types", status: "done", priority: "P0" },
      { title: "Expanded SPARQL: +employer, +buried, +significant event", status: "done", priority: "P0" },
      { title: "Hero panel with person photo + description", status: "done", priority: "P0" },
      { title: "Play-tour mode: camera auto-pans between pins chronologically", status: "done", priority: "P0" },
      { title: "Highlight active event during tour", status: "done", priority: "P0" },
      { title: "Per-person static landing pages (top 1000 figures)", status: "todo", priority: "P0" },
      { title: "Dynamic OG image per person", status: "todo", priority: "P1" },
      { title: "Year tooltip floating near each pin", status: "todo", priority: "P1" },
      { title: "Timeline scrubber (drag year → filter events)", status: "todo", priority: "P1" },
      { title: "Related figures at bottom of person page", status: "todo", priority: "P1" },
      { title: "Group mode: compare 2–3 lives on one globe", status: "todo", priority: "P2" },
      { title: "Wikipedia excerpt per event location", status: "todo", priority: "P2" },
      { title: "Collections (writers, scientists, musicians)", status: "todo", priority: "P2" },
      { title: "Family-tree overlay", status: "todo", priority: "P3" },
    ],
  },
];

export function countStatuses() {
  let done = 0,
    inProgress = 0,
    todo = 0;
  for (const s of BACKLOG) {
    for (const t of s.tasks) {
      if (t.status === "done") done++;
      else if (t.status === "in-progress") inProgress++;
      else todo++;
    }
  }
  return { done, inProgress, todo, total: done + inProgress + todo };
}
